generic: backport 5.16 fix for hv utils build failure
Backports following fix:

 hv: utils: add PTP_1588_CLOCK to Kconfig to fix build

 The hyperv utilities use PTP clock interfaces and should depend a
 a kconfig symbol such that they will be built as a loadable module or
 builtin so that linker errors do not happen.

 Prevents these build errors:

 ld: drivers/hv/hv_util.o: in function `hv_timesync_deinit':
 hv_util.c:(.text+0x37d): undefined reference to `ptp_clock_unregister'
 ld: drivers/hv/hv_util.o: in function `hv_timesync_init':
 hv_util.c:(.text+0x738): undefined reference to `ptp_clock_register'

References: https://lore.kernel.org/stable/20220328093115.7486-1-ynezz@true.cz/T/#u
Signed-off-by: Petr Štetiar <ynezz@true.cz>