at91: 6.1: import patch to fix pinctrl unused function warning
Fixes error in the form of [0]:
  drivers/pinctrl/pinctrl-at91.c:1668:12: error: 'at91_gpio_resume' defined but not used [-Werror=unused-function]
   1668 | static int at91_gpio_resume(struct device *dev)
        |            ^~~~~~~~~~~~~~~~
  drivers/pinctrl/pinctrl-at91.c:1650:12: error: 'at91_gpio_suspend' defined but not used [-Werror=unused-function]
   1650 | static int at91_gpio_suspend(struct device *dev)
        |            ^~~~~~~~~~~~~~~~~

[0] - https://lore.kernel.org/all/20221215164301.934805-1-arnd@kernel.org/

Signed-off-by: Nick Hainke <vincent@systemli.org>