kernel: kmod-ltq-deu: rename some sha1 functions
They are conflict with the kernel crypto library on 6.18 kernel.
Fixes:

ifxmips_sha1.c:83:8: error: redefinition of 'struct sha1_ctx'
   83 | struct sha1_ctx {
      |        ^~~~~~~~
In file included from ifxmips_sha1.c:50:
/workspaces/openwrt/build_dir/target-mips_24kc_musl/linux-lantiq_xway/linux-6.18.21/include/crypto/sha1.h:50:8: note: originally defined here
   50 | struct sha1_ctx {
      |        ^~~~~~~~
ifxmips_sha1.c:164:12: error: conflicting types for 'sha1_update'; have 'int(struct shash_desc *, const u8 *, unsigned int)' {aka 'int(struct shash_desc *, const unsigned char *, unsigned int)'}
  164 | static int sha1_update(struct shash_desc * desc, const u8 *data,
      |            ^~~~~~~~~~~
/workspaces/openwrt/build_dir/target-mips_24kc_musl/linux-lantiq_xway/linux-6.18.21/include/crypto/sha1.h:76:6: note: previous declaration of 'sha1_update' with type 'void(struct sha1_ctx *, const u8 *, size_t)' {aka 'void(struct sha1_ctx *, const unsigned char *, unsigned int)'}
   76 | void sha1_update(struct sha1_ctx *ctx, const u8 *data, size_t len);
      |      ^~~~~~~~~~~
ifxmips_sha1.c:195:12: error: conflicting types for 'sha1_final'; have 'int(struct shash_desc *, u8 *)' {aka 'int(struct shash_desc *, unsigned char *)'}
  195 | static int sha1_final(struct shash_desc *desc, u8 *out)
      |            ^~~~~~~~~~
/workspaces/openwrt/build_dir/target-mips_24kc_musl/linux-lantiq_xway/linux-6.18.21/include/crypto/sha1.h:87:6: note: previous declaration of 'sha1_final' with type 'void(struct sha1_ctx *, u8 *)' {aka 'void(struct sha1_ctx *, unsigned char *)'}
   87 | void sha1_final(struct sha1_ctx *ctx, u8 out[SHA1_DIGEST_SIZE]);
      |      ^~~~~~~~~~

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
Link: https://github.com/openwrt/openwrt/pull/22921
Signed-off-by: Robert Marko <robimarko@gmail.com>